import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  const checkAuth = () => {};
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>hi evry one</h1>
    </div>
  );
};

export default Home;
